-- ============================================================
-- NEW RECIPES + DETAILS SQL
-- Run in Supabase SQL Editor
-- ============================================================

-- PART 1: Fix Hungry Hobby URLs
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-pesto-chicken-pasta/' WHERE id = 33;
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-sesame-chicken/' WHERE id = 34;
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-chicken-shawarma/' WHERE id = 35;
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-salsa-verde-chicken/' WHERE id = 36;
UPDATE recipes SET url = 'https://hungryhobby.net/slowcooker-bbq-wings/' WHERE id = 37;
UPDATE recipes SET url = 'https://hungryhobby.net/barbecue-pulled-pork-lettuce-wraps-with-healthy-coleslaw-2/' WHERE id = 38;
UPDATE recipes SET url = 'https://hungryhobby.net/crockpot-turkey-meatballs/' WHERE id = 39;
UPDATE recipes SET url = 'https://hungryhobby.net/turkey-meatball-subs/' WHERE id = 40;
UPDATE recipes SET url = 'https://hungryhobby.net/chipotle-chicken-tacos/' WHERE id = 41;
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-adobo-chicken/' WHERE id = 42;
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-meatball-soup/' WHERE id = 43;
UPDATE recipes SET url = 'https://hungryhobby.net/easy-crockpot-mexican-pork-carnitas-recipe-video/' WHERE id = 44;
UPDATE recipes SET url = 'https://hungryhobby.net/easy-crockpot-thai-chicken-recipe/' WHERE id = 45;
UPDATE recipes SET url = 'https://hungryhobby.net/slow-cooker-chicken-tortilla-soup/' WHERE id = 46;
UPDATE recipes SET url = 'https://hungryhobby.net/crispy-slow-cooker-beef-carnitas/' WHERE id = 47;
UPDATE recipes SET url = 'https://flexibledietinglifestyle.com/472-cal-freezer-breakfast-burritos/' WHERE id = 1;
UPDATE recipes SET url = 'https://kaynutrition.com/meal-prep-breakfast-burritos/' WHERE id = 2;

-- PART 2: New recipes
INSERT INTO recipes (id, name, category, protein, method) VALUES
(71, 'Slow Cooker Breakfast Casserole', 'Breakfast', 'Eggs', 'Slow Cooker'),
(72, 'Veggie-Loaded Egg Scramble', 'Breakfast', 'Eggs', 'Stovetop'),
(73, 'Protein Yogurt Bowl', 'Breakfast', 'Protein Powder', 'No Cook'),
(74, 'Cauliflower Egg Fried Rice Breakfast Bowl', 'Breakfast', 'Eggs', 'Stovetop'),
(75, 'Savory Egg Muffin Veggie Bake', 'Breakfast', 'Eggs', 'Oven')
ON CONFLICT (id) DO NOTHING;

-- PART 3: recipe_details for all recipes
INSERT INTO recipe_details (recipe_id, ingredients, steps, updated_at) VALUES
(1, ARRAY['1 lb ground turkey or beef','6 large eggs','1 green bell pepper, diced','1 yellow onion, diced','1 cup shredded cheddar cheese','8 large flour tortillas (10-inch)','1 cup frozen tater tots, baked','Salt and pepper to taste','Cooking spray'], ARRAY['Cook tater tots in air fryer or oven per package directions.','Brown ground meat in a skillet over medium-high heat. Drain and set aside.','In same skillet, saute diced pepper and onion until softened, about 5 minutes.','Scramble eggs in the skillet with vegetables. Season with salt and pepper.','Lay out tortillas. Divide meat, egg mixture, tater tots, and cheese evenly among tortillas.','Roll burritos tightly, folding in sides. Wrap each in foil.','Freeze. Reheat in air fryer at 350F for 12-15 min or microwave 2-3 min.'], now()),
(2, ARRAY['3 tablespoons olive oil','1 pound white potatoes, cut into 1/2-inch cubes','1/2 teaspoon garlic powder','1/2 teaspoon salt','1/8 teaspoon black pepper','1 pound pork or turkey sausage, casings removed','1 onion, diced','1 green bell pepper, seeded and diced','2 tablespoons butter','12 eggs','1 cup shredded cheddar cheese','8 flour tortillas (10-inch)','Salsa','Sour cream','Avocado'], ARRAY['Preheat oven to 400F. Line a baking sheet with parchment paper.','Place cubed potatoes on sheet, drizzle with 2 tbsp olive oil, sprinkle with garlic powder, salt, and pepper. Roast 25-30 min until golden.','Whisk eggs in a large bowl and set aside.','Warm remaining olive oil in a large skillet over medium-high. Cook sausage, breaking into pieces, until browned. Remove and set aside.','In same pan, cook onion and bell pepper 3-4 min until softened.','Melt butter in pan over low-medium heat. Add eggs and scramble gently until just set.','Lay tortillas flat. Divide potatoes, sausage, eggs, veggies, and cheese evenly among them.','Fold left and right sides in, then roll up from bottom tightly.','Optional: sear burritos seam-side down 1-2 min to seal.','Wrap individually in parchment then foil. Refrigerate up to 5 days or freeze up to 3 months.'], now()),
(33, ARRAY['1 3/4 cups unsalted chicken broth','1 cup pesto sauce, divided','1.5 lbs boneless skinless chicken thighs','1.5 lbs boneless skinless chicken breast','8 oz high protein pasta, dry','3 cups spinach','1/2 cup shredded mozzarella'], ARRAY['Pour chicken broth into slow cooker. Add chicken. Pour 1/2 cup pesto over chicken.','Cook on HIGH 3-4 hours or LOW 6-7 hours until chicken shreds easily.','Remove chicken and shred. Pour dry pasta into slow cooker liquid. Cook on HIGH 20-30 min until tender.','Add chicken back in with remaining 1/2 cup pesto. Fold in spinach until wilted.','Top with mozzarella, cover 5 min until melted. Serve warm.'], now()),
(34, ARRAY['1.5 lbs boneless skinless chicken breast','1.5 lbs boneless skinless chicken thighs','3 cloves garlic, minced','1/2 cup coconut aminos','1/3 cup ketchup','1/4 cup honey','1 tablespoon rice vinegar','1 tablespoon cornstarch','1 tablespoon water','Sesame seeds for garnish','Green onion for garnish'], ARRAY['Whisk together coconut aminos, ketchup, honey, rice vinegar, and garlic.','Add chicken to slow cooker. Pour sauce over top, wiggle chicken so sauce gets underneath.','Cook on HIGH 3-4 hours or LOW 4-6 hours until chicken reaches 165F.','Shred chicken. Mix cornstarch with water, stir into sauce. Cook on HIGH 10 min to thicken.','Garnish with sesame seeds and green onion. Serve over rice.'], now()),
(35, ARRAY['3 cloves garlic, minced','1 tablespoon coriander','1 tablespoon cardamom','1/4 teaspoon cayenne pepper','1 tablespoon paprika','1 teaspoon sumac','2 teaspoons sea salt','2 teaspoons sugar','1 whole lemon, juiced','1/3 cup water','1 lb boneless skinless chicken breast','2 lbs boneless skinless chicken thighs'], ARRAY['Mix seasonings and garlic with chicken directly in slow cooker.','Add lemon juice and water. Close lid.','Cook on HIGH 3-4 hours or LOW 4-6 hours until chicken reaches 165F and shreds easily.','Shred chicken and stir into juices.','Optional: spread on foil-lined sheet pan and broil 5-7 min for crispy edges. Serve with pita, tzatziki, and salad.'], now()),
(36, ARRAY['16 oz salsa verde (one jar)','1 white onion, cut into strips','2-3 lbs chicken breast, defrosted'], ARRAY['Pour half the salsa verde on the bottom of the slow cooker. Add chicken. Top with onion strips. Pour remaining salsa verde over everything.','Cook on HIGH 4 hours or LOW 6-8 hours. Shred chicken with two forks.','Serve in tacos, burrito bowls, over rice, or with chips.'], now()),
(37, ARRAY['3 lbs chicken wings, split, tips removed','1 cup BBQ sauce','1/4 cup honey','2 tablespoons hot sauce (optional)','1 teaspoon garlic powder','1 teaspoon smoked paprika','Salt and pepper to taste'], ARRAY['Season wings with garlic powder, paprika, salt, and pepper.','Place wings in slow cooker. Mix BBQ sauce, honey, and hot sauce; pour over wings.','Cook on LOW 4-5 hours or HIGH 2-3 hours until cooked through.','Optional: transfer to foil-lined baking sheet and broil 5-8 min for crispy skin.','Serve with extra BBQ sauce.'], now()),
(38, ARRAY['3 lbs pork shoulder or butt','1 cup BBQ sauce','1/2 cup chicken or beef broth','1 tablespoon brown sugar','1 teaspoon garlic powder','1 teaspoon onion powder','1 teaspoon smoked paprika','Salt and pepper to taste','Butter lettuce leaves for wrapping','Coleslaw mix for topping'], ARRAY['Season pork with garlic powder, onion powder, paprika, salt, and pepper.','Place pork in slow cooker. Mix BBQ sauce, broth, and brown sugar; pour over pork.','Cook on LOW 8-10 hours or HIGH 4-6 hours until fork-tender.','Shred pork with two forks and stir into juices.','Serve in butter lettuce leaves topped with coleslaw.'], now()),
(39, ARRAY['2 lbs 93% lean ground turkey','1 tbsp dried onion flakes','1/2 cup chopped fresh parsley','1/3 cup chopped fresh basil','1 tbsp garlic powder','1 tbsp Italian seasoning','1/2 tbsp salt','1/2 tsp black pepper','1/4 cup oat flour','36 ounces marinara sauce'], ARRAY['Combine turkey, onion flakes, parsley, basil, garlic powder, Italian seasoning, salt, pepper, and oat flour. Mix until just combined.','Roll into 1.5-inch meatballs.','Add 1/3 of sauce to bottom of slow cooker. Add meatballs. Pour remaining sauce over top.','Cook on HIGH 3-4 hours or LOW 4-6 hours. Do not stir.','Serve over pasta, zucchini noodles, or as subs.'], now()),
(40, ARRAY['2 lbs 93% lean ground turkey','1 tbsp dried onion flakes','1/2 cup chopped fresh parsley','1/3 cup chopped fresh basil','1 tbsp garlic powder','1 tbsp Italian seasoning','1/2 tbsp salt','1/2 tsp black pepper','1/4 cup oat flour','36 ounces marinara sauce','8 sub rolls','2 tbsp olive oil','8 oz mozzarella','8 oz ricotta','1/2 cup fresh basil'], ARRAY['Combine turkey, onion flakes, parsley, basil, garlic powder, Italian seasoning, salt, pepper, and oat flour. Roll into 1.5-inch meatballs.','Add 1/3 of sauce to slow cooker. Add meatballs. Pour remaining sauce over top.','Cook on HIGH 3-4 hours or LOW 4-6 hours. Do not stir.','Preheat oven to 400F. Brush rolls with olive oil. Toast 3-8 min until golden.','Build subs with meatballs, sauce, ricotta, mozzarella, and fresh basil.'], now()),
(41, ARRAY['1 teaspoon Celtic or Himalayan salt','1 tablespoon smoked paprika','1/2 teaspoon dried oregano','1 tablespoon chipotle pepper powder','1/4 cup chicken broth','1/4 cup lime juice','1 onion, chopped','2 cloves garlic, minced','2 lbs chicken breasts','1 tablespoon avocado oil','1 avocado, sliced','1-2 Roma tomatoes, chopped','1 small can black olives','Green onions for garnish','12 cassava or corn tortillas'], ARRAY['Add chicken broth, lime juice, onion, and garlic to slow cooker.','Combine salt, paprika, oregano, and chipotle powder. Rub all over chicken.','Place chicken on top of onion mixture.','Cook on HIGH 4-6 hours until chicken reaches 165F and shreds easily.','Shred chicken and stir into juices. Build tacos with avocado, tomato, olives, and green onions.'], now()),
(42, ARRAY['3 lbs boneless skinless chicken thighs','1/2 cup white distilled vinegar','1/2 cup coconut aminos or soy sauce','6 cloves garlic, crushed','1 tsp black peppercorns','2-3 bay leaves','1/2 sweet onion, chopped','2 tablespoons coconut sugar or brown sugar'], ARRAY['Add vinegar, coconut aminos, peppercorns, sugar, bay leaves, half the onion, and garlic to slow cooker. Stir.','Add chicken and toss in sauce. Top with remaining onion.','Cook on LOW 6-8 hours or HIGH 3-4 hours until chicken is tender.','Remove bay leaves. Serve garnished with green onions.','Optional: drain liquid, reduce in saucepan, pour thickened sauce back over chicken.'], now()),
(43, ARRAY['32 oz frozen precooked meatballs','1 yellow onion, chopped','3 cloves garlic, minced','2 cans diced tomatoes','4 cups chicken or vegetable broth','4 cups water','1 tbsp Italian seasoning','8 oz chickpea pasta','3-4 cups spinach','1/4 cup grated Parmesan (garnish)','1/4 cup fresh parsley or basil (garnish)'], ARRAY['Add all ingredients except pasta and greens to slow cooker. Stir.','Cook on LOW 6-8 hours or HIGH 3-4 hours.','15-20 min before serving, stir in pasta. Cook until tender.','Turn off slow cooker. Stir in spinach until wilted.','Ladle into bowls. Garnish with Parmesan and fresh herbs.'], now()),
(44, ARRAY['4 lbs pork shoulder or butt','2 teaspoons dried oregano','2 teaspoons coconut sugar','1 teaspoon dried basil','1 teaspoon smoked paprika','1 teaspoon chipotle chile powder','1 tablespoon fine sea salt','1/2 tsp black pepper','1 tablespoon avocado oil','12 garlic cloves','1 onion, sliced','1 cup water','1-2 limes'], ARRAY['Combine oregano, coconut sugar, basil, paprika, chipotle, salt, and pepper. Rub all over pork.','Heat oil in large pan over medium-high. Brown all sides of pork 1-2 min per side.','Cut 12 small slits in pork and stuff garlic cloves into slits.','Add water and onion to slow cooker. Place pork on top. Squeeze lime juice over everything.','Cook on HIGH 4-6 hours or LOW 6-8 hours until pork shreds easily.','Shred pork. Spread on foil-lined sheet pan and broil 3-6 min for crispy edges.'], now()),
(45, ARRAY['2 lbs boneless skinless chicken thighs','1/4 cup coconut aminos or soy sauce','2 tablespoons natural peanut butter','2 tablespoons lime juice','1 tablespoon honey','1 tablespoon rice vinegar','2 cloves garlic, minced','1 teaspoon ginger, grated','1 teaspoon sriracha','Butter lettuce leaves','Shredded carrots','Chopped cilantro','Chopped peanuts','Sliced green onions'], ARRAY['Whisk together coconut aminos, peanut butter, lime juice, honey, rice vinegar, garlic, ginger, and sriracha.','Place chicken in slow cooker. Pour sauce over top.','Cook on LOW 4-6 hours or HIGH 2-3 hours until very tender.','Shred chicken and stir into sauce.','Serve in butter lettuce cups topped with carrots, cilantro, peanuts, and green onions.'], now()),
(46, ARRAY['2 lbs chicken breast','4 cups chicken broth','16 oz red enchilada sauce','28 oz canned fire-roasted diced tomatoes','4 oz canned fire-roasted green chiles','2 cans pinto beans, rinsed','1 white onion, chopped','2 cloves garlic, minced','1 jalapeno, chopped and de-seeded','8 corn tortillas','Cooking spray','Sea salt','2 avocados (topping)','1 cup cilantro (topping)','1 cup sour cream (topping)','1 cup Mexican cheese (topping)','3 green onions (garnish)'], ARRAY['Place chicken in slow cooker. Add onion, garlic, jalapeno, broth, enchilada sauce, tomatoes, green chiles, and beans.','Cook on HIGH 4-6 hours or LOW 6-8 hours until chicken shreds easily. Shred chicken and stir back in.','For tortilla strips: preheat oven to 400F. Cut tortillas into 1/4-inch strips. Spread on sprayed parchment-lined sheet. Spray tops. Bake 10 min, shake, bake 5 more min until crispy.','Ladle soup into bowls. Top with tortilla strips, avocado, sour cream, cheese, cilantro, and green onions.'], now()),
(47, ARRAY['2 lb steak or roast','2 cups fresh orange juice','1 jalapeno, stem removed','1 medium yellow onion','1/4 cup lime juice','1/2 cup beef or vegetable broth','1/2 cup salsa','5 cloves garlic','1 teaspoon cumin','1/2 - 2 teaspoon chipotle chili pepper','1 tsp oregano','1 tsp black pepper','1 tbsp salt','1 avocado','8 tortillas'], ARRAY['Mix cumin, chipotle, oregano, black pepper, and salt. Rub all over meat.','Cut 4 slits in meat and stuff garlic into each slit.','Blend lime juice, orange juice, jalapeno, half the onion, broth, and one garlic clove until smooth.','Pour half the blend into slow cooker. Add meat surrounded by remaining onion. Pour rest over top.','Cook on LOW 7-8 hours or HIGH 4-6 hours. Shred meat.','Optional: broil on foil-lined sheet pan 3-5 min for crispy edges.','Serve in tortillas with lazy guacamole (mash avocado with salsa).'], now()),
(68, ARRAY['3 boneless skinless chicken breasts (about 2 lbs)','2 tsp chili powder','1/2 tsp garlic powder','1/2 tsp onion powder','16 oz salsa'], ARRAY['Place chicken in slow cooker. Sprinkle chili powder, garlic powder, and onion powder over top.','Pour salsa over chicken.','Cook on HIGH 2.5 hours or LOW 5 hours.','Test chicken - shreds easily when done. If not, cook 30 more min.','Shred with two forks and stir into salsa and juices. Serve over rice, in tacos, or burrito bowls.'], now()),
(69, ARRAY['26 oz bag frozen meatballs','10 oz can cream of mushroom soup','2 cups beef broth','1 tbsp Worcestershire sauce','1 tbsp steak sauce','1 tbsp Dijon mustard','1/2 tsp salt','1/2 tsp pepper','1 tsp parsley flakes','1 tsp onion powder','1 tbsp minced garlic','1 onion, chopped','1/2 cup sour cream','12 oz egg noodles'], ARRAY['Add meatballs to slow cooker. Add cream of mushroom soup, beef broth, Worcestershire, steak sauce, and Dijon. Stir.','Add salt, pepper, parsley, onion powder, garlic, and chopped onion.','Cook on LOW 4-6 hours.','Boil egg noodles per package directions. Drain.','Stir sour cream and noodles into slow cooker. Top with dried parsley to serve.'], now()),
(70, ARRAY['3 boneless chicken breasts','1 tablespoon minced garlic','1 can crushed tomatoes (28 oz)','1 can tomato sauce (15 oz)','1 tsp salt','1 tsp black pepper','2 tsp Italian seasoning','4 cups chicken broth','1 cup Parmesan cheese, shaved','1 cup heavy whipping cream','8 oz rotini pasta, uncooked','1/2 cup bread crumbs','1 tablespoon butter','1 1/2 cups shredded mozzarella'], ARRAY['Add chicken, garlic, crushed tomatoes, tomato sauce, salt, pepper, Italian seasoning, and broth to slow cooker.','Cook on LOW 6-8 hours or HIGH 3-4 hours.','Shred chicken. Stir in Parmesan, heavy cream, and rotini. Cook on HIGH 20-30 min until pasta is tender.','Saute breadcrumbs in butter in a small pan until golden.','Ladle into bowls. Top with mozzarella and toasted breadcrumbs.'], now()),
(71, ARRAY['4 oz Pace Picante sauce or chunky salsa','4 corn tortillas, cut into strips','1 red bell pepper, chopped','1 green bell pepper, chopped','1/2 jalapeno, chopped','1.5 cups shredded Mexican cheese','12 large eggs','1/2 tsp salt','1/4 tsp black pepper','1/2 tablespoon taco seasoning'], ARRAY['Grease slow cooker with oil.','Pour salsa on bottom and spread evenly.','Layer tortilla strips, then bell peppers, jalapeno, and cheese.','Whisk eggs with salt, pepper, and taco seasoning. Pour into slow cooker and gently stir.','Cook on HIGH 4-5 hours or LOW 6-8 hours. Tilt lid slightly if excess moisture builds up.'], now()),
(72, ARRAY['2 large eggs','Handful of mushrooms, sliced','Handful of bell peppers, sliced','Handful of fresh spinach','1 tsp avocado oil','Salt and pepper to taste'], ARRAY['Heat avocado oil in non-stick skillet over medium heat.','Add mushrooms and peppers. Saute 3-4 minutes until softened.','Add spinach and stir until wilted, about 1 minute.','Crack eggs into pan. Scramble with vegetables until just set.','Season with salt and pepper. Serve immediately.'], now()),
(73, ARRAY['1 Awaken180 vanilla or chocolate protein packet','2-4 tbsp cold water','Finely diced cucumber or zucchini','Cinnamon or nutmeg to taste'], ARRAY['Empty protein packet into a bowl.','Add 2-4 tbsp cold water and stir vigorously until thick like yogurt. Add water 1 tbsp at a time to control thickness.','Top with finely diced cucumber or zucchini.','Sprinkle with cinnamon or nutmeg. Serve immediately.'], now()),
(74, ARRAY['2 eggs or egg whites','1 cup cauliflower rice','Handful of fresh spinach or shredded cabbage','Sea salt and pepper to taste','1 tsp avocado oil'], ARRAY['Heat avocado oil in non-stick skillet over medium-high heat.','Add cauliflower rice. Cook 3-4 minutes, stirring, until slightly golden.','Push cauliflower to side. Add eggs and scramble until just set, then mix together.','Add spinach or cabbage and stir until wilted.','Season with sea salt and pepper. Serve hot.'], now()),
(75, ARRAY['1 cup mixed diced vegetables (peppers, onion, zucchini, mushrooms)','2 whole eggs','1/2 cup liquid egg whites','Sea salt to taste','Black pepper to taste','Garlic powder to taste','Cooking spray'], ARRAY['Preheat oven to 350F. Grease a muffin tin or small baking dish with cooking spray.','Divide diced vegetables evenly among muffin cups.','Whisk whole eggs and egg whites together. Season with sea salt, pepper, and garlic powder.','Pour egg mixture over vegetables, filling cups about 3/4 full.','Bake 20-25 minutes until eggs are set and edges are lightly golden. Cool 5 minutes before removing.'], now())
ON CONFLICT (recipe_id) DO UPDATE SET
  ingredients = EXCLUDED.ingredients,
  steps = EXCLUDED.steps,
  updated_at = EXCLUDED.updated_at;
