-- Structured ingredients for new recipes (IDs 33-47, 68-75, updated 1 & 2)
-- Run in Supabase AFTER structured_ingredients.sql

-- Remove any existing entries for these IDs first
DELETE FROM recipe_ingredients WHERE recipe_id IN (1,2,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,68,69,70,71,72,73,74,75);

INSERT INTO recipe_ingredients (recipe_id, amount, amount_fraction, measurement, ingredient, notes, sort_order) VALUES
(41, 1.0, NULL, 'tsp', 'Celtic or Himalayan salt', NULL, 1),
(41, 1.0, NULL, 'tbsp', 'smoked paprika', NULL, 2),
(41, 0.5, '1/2', 'tsp', 'oregano', 'dried', 3),
(41, 1.0, NULL, 'tbsp', 'chipotle peppers', 'powder', 4),
(41, 0.25, '1/4', 'cup', 'chicken broth', 'for instant pot or 0.75 cup for the slow cooker', 5),
(41, 0.25, '1/4', 'cup', 'lime juice', 'for instant pot or slow cooker', 6),
(41, 1.0, NULL, NULL, 'onion', 'chopped', 7),
(41, 2.0, NULL, 'clove', 'garlic', 'minced', 8),
(41, 2.0, NULL, 'lb', 'chicken breasts', NULL, 9),
(41, 1.0, NULL, 'tbsp', 'avocado oil', NULL, 10),
(41, 1.0, NULL, NULL, 'avocado', 'peeled and sliced', 11),
(41, 1.0, NULL, NULL, 'Roma tomatoes', 'chopped', 12),
(41, 1.0, NULL, NULL, 'small can black olives', NULL, 13),
(41, NULL, NULL, NULL, 'green onions for garnish', NULL, 14),
(41, 12.0, NULL, NULL, 'cassava tortillas', 'or corn tortillas', 15),
(68, 3.0, NULL, NULL, 'boneless skinless chicken breasts', 'about 2 lbs', 1),
(68, 2.0, NULL, 'tsp', 'chili powder', NULL, 2),
(68, 0.5, '1/2', 'tsp', 'garlic powder', NULL, 3),
(68, 0.5, '1/2', 'tsp', 'onion powder', NULL, 4),
(68, 16.0, NULL, NULL, 'oz. salsa', NULL, 5),
(40, 2.0, NULL, 'lb', '93% lean ground turkey', 'can sub chicken', 1),
(40, 1.0, NULL, 'tbsp', 'dried onion flakes', NULL, 2),
(40, 0.5, '1/2', 'cup', 'chopped fresh parsley', NULL, 3),
(40, 0.3333, '1/3', 'cup', 'chopped fresh basil', NULL, 4),
(40, 1.0, NULL, 'tbsp', 'garlic powder', NULL, 5),
(40, 1.0, NULL, 'tbsp', 'Italian seasoning', NULL, 6),
(40, 0.5, '1/2', 'tbsp', 'salt', NULL, 7),
(40, 0.5, '1/2', 'tsp', 'black pepper', NULL, 8),
(40, 0.25, '1/4', 'cup', 'oat flour', NULL, 9),
(40, 36.0, NULL, 'oz', 'marinara sauce', NULL, 10),
(40, 8.0, NULL, NULL, 'rolls', NULL, 11),
(40, 2.0, NULL, 'tbsp', 'olive oil', NULL, 12),
(40, 8.0, NULL, 'oz', 'mozzarella', NULL, 13),
(40, 8.0, NULL, 'oz', 'ricotta', NULL, 14),
(40, 0.5, '1/2', 'cup', 'fresh basil', NULL, 15),
(70, 3.0, NULL, NULL, 'boneless chicken breasts', NULL, 1),
(70, 1.0, NULL, 'tbsp', 'minced garlic', NULL, 2),
(70, 1.0, NULL, 'can', 'crushed tomatoes', '28 oz', 3),
(70, 1.0, NULL, 'can', 'tomato sauce', '15 oz', 4),
(70, 1.0, NULL, 'tsp', 'salt', NULL, 5),
(70, 1.0, NULL, 'tsp', 'ground black pepper', NULL, 6),
(70, 2.0, NULL, 'tsp', 'Italian Seasoning', NULL, 7),
(70, 4.0, NULL, 'cup', 'chicken broth', NULL, 8),
(70, 1.0, NULL, 'cup', 'parmesan cheese', 'freshly shaved', 9),
(70, 1.0, NULL, 'cup', 'heavy whipping cream', NULL, 10),
(70, 8.0, NULL, 'oz', 'rotini pasta', 'uncooked', 11),
(70, 0.5, '1/2', 'cup', 'bread crumbs', NULL, 12),
(70, 1.0, NULL, 'tbsp', 'butter', NULL, 13),
(70, 1.5, '1/2', 'cup', 'shredded mozzarella', NULL, 14),
(69, 26.0, NULL, 'oz', 'frozen meatballs', NULL, 1),
(69, 10.0, NULL, 'oz', 'cream of mushroom soup', NULL, 2),
(69, 2.0, NULL, 'cup', 'beef broth', NULL, 3),
(69, 1.0, NULL, 'tbsp', 'Worcestershire sauce', NULL, 4),
(69, 1.0, NULL, 'tbsp', 'Steak Sauce', NULL, 5),
(69, 1.0, NULL, 'tbsp', 'Dijon mustard', NULL, 6),
(69, 0.5, '1/2', 'tsp', 'each of salt and pepper', NULL, 7),
(69, 1.0, NULL, 'tsp', 'each of parsley flakes and onion powder', NULL, 8),
(69, 1.0, NULL, 'tbsp', 'minced garlic', NULL, 9),
(69, 1.0, NULL, NULL, 'onion', 'chopped', 10),
(69, 0.5, '1/2', 'cup', 'sour cream', NULL, 11),
(69, 12.0, NULL, 'oz', 'bag egg noddles', NULL, 12),
(39, 2.0, NULL, 'lb', '93% lean ground turkey', 'can sub chicken', 1),
(39, 1.0, NULL, 'tbsp', 'dried onion flakes', NULL, 2),
(39, 0.5, '1/2', 'cup', 'chopped fresh parsley', NULL, 3),
(39, 0.3333, '1/3', 'cup', 'chopped fresh basil', NULL, 4),
(39, 1.0, NULL, 'tbsp', 'garlic powder', NULL, 5),
(39, 1.0, NULL, 'tbsp', 'Italian seasoning', NULL, 6),
(39, 0.5, '1/2', 'tbsp', 'salt', NULL, 7),
(39, 0.5, '1/2', 'tsp', 'black pepper', NULL, 8),
(39, 0.25, '1/4', 'cup', 'oat flour', NULL, 9),
(39, 36.0, NULL, 'oz', 'marinara sauce', NULL, 10),
(44, 4.0, NULL, 'lb', 'pork shoulder or pork butt', NULL, 1),
(44, 2.0, NULL, 'tsp', 'dried oregano', NULL, 2),
(44, 2.0, NULL, 'tsp', 'coconut sugar', NULL, 3),
(44, 1.0, NULL, 'tsp', 'dried basil', NULL, 4),
(44, 1.0, NULL, 'tsp', 'smoked paprika', NULL, 5),
(44, 1.0, NULL, 'tsp', 'chipotle chile powder', NULL, 6),
(44, 1.0, NULL, 'tbsp', 'fine sea salt', NULL, 7),
(44, 0.5, '1/2', 'tsp', 'black pepper', NULL, 8),
(44, 1.0, NULL, 'tbsp', 'avocado oil', NULL, 9),
(44, 12.0, NULL, NULL, 'garlic cloves', NULL, 10),
(44, 1.0, NULL, NULL, 'onion', 'sliced', 11),
(44, 1.0, NULL, 'cup', 'water', NULL, 12),
(44, 1.0, NULL, NULL, 'limes', NULL, 13),
(2, 3.0, NULL, NULL, 'tablespoonsolive oil', NULL, 1),
(2, 1.0, NULL, NULL, 'poundwhite potatoes', 'cut into 1/2-inch cubes', 2),
(2, 0.5, '1/2', NULL, 'teaspoongarlic powder', NULL, 3),
(2, 0.5, '1/2', NULL, 'teaspoonsalt', NULL, 4),
(2, 0.125, NULL, NULL, 'teaspoonblack pepper', NULL, 5),
(2, 1.0, NULL, NULL, 'poundpork orturkey sausage', 'casings removed', 6),
(2, 1.0, NULL, NULL, 'onion', 'diced', 7),
(2, 1.0, NULL, NULL, 'green bell pepper', 'seeded and diced', 8),
(2, 2.0, NULL, NULL, 'tablespoonsbutter', NULL, 9),
(2, 12.0, NULL, NULL, 'eggs', NULL, 10),
(2, 1.0, NULL, NULL, 'cupshreddedcheddar cheese', NULL, 11),
(2, 8.0, NULL, NULL, 'flour tortillas', '10-inch', 12),
(2, NULL, NULL, NULL, 'Salsa', NULL, 13),
(2, NULL, NULL, NULL, 'Sour cream', NULL, 14),
(2, NULL, NULL, NULL, 'Avocado', NULL, 15),
(42, 3.0, NULL, 'lb', 'chicken thighs', 'boneless, skinless', 1),
(42, 0.5, '1/2', 'cup', 'white distilled vinegar', NULL, 2),
(42, 0.5, '1/2', 'cup', 'coconut aminos', 'or soy sauce', 3),
(42, 6.0, NULL, 'clove', 'garlic', 'crushed or minced', 4),
(42, 1.0, NULL, 'tsp', 'black peppercorns', NULL, 5),
(42, 2.0, NULL, NULL, 'bay leaves', NULL, 6),
(42, 0.5, '1/2', NULL, 'sweet onion', 'chopped', 7),
(42, 2.0, NULL, 'tbsp', 'coconut sugar', 'or brown sugar', 8),
(47, 2.0, NULL, 'lb', 'steak or roast', NULL, 1),
(47, 2.0, NULL, 'cup', 'orange juice', 'fresh, not from concentrate', 2),
(47, 1.0, NULL, NULL, 'jalapeno', 'stem removed', 3),
(47, 1.0, NULL, NULL, 'medium yellow onion', 'skin removed, ends removed', 4),
(47, NULL, NULL, NULL, 'lime juice', ' 0.25 cup', 5),
(47, 0.5, '1/2', 'cup', 'vegetable or beef broth', 'may need more', 6),
(47, 0.5, '1/2', 'cup', 'salsa', NULL, 7),
(47, 5.0, NULL, 'clove', 'garlic', NULL, 8),
(47, 1.0, NULL, 'tsp', 'cumin', NULL, 9),
(47, 0.5, '1/2', 'tsp', 'chipotle chili pepper', NULL, 10),
(47, 1.0, NULL, 'tsp', 'oregano', NULL, 11),
(47, 1.0, NULL, 'tsp', 'black pepper', NULL, 12),
(47, 1.0, NULL, 'tbsp', 'salt', NULL, 13),
(47, 1.0, NULL, NULL, 'avocado', NULL, 14),
(47, 0.5, '1/2', 'cup', 'salsa', NULL, 15),
(47, 8.0, NULL, NULL, 'tortillas', NULL, 16),
(71, 4.0, NULL, 'oz', 'Pace® Picante sauce or chunky salsa', NULL, 1),
(71, 4.0, NULL, NULL, 'corn tortillas', 'cut into strips', 2),
(71, 1.0, NULL, NULL, 'red bell pepper', 'deveined, chopped', 3),
(71, 1.0, NULL, NULL, 'green bell pepper', 'deveined, chopped', 4),
(71, 0.5, '1/2', NULL, 'jalapeno', 'deveined, chopped', 5),
(71, 1.5, '1/2', 'cup', 'shredded mexican cheese', NULL, 6),
(71, 12.0, NULL, NULL, 'large eggs', NULL, 7),
(71, 0.5, '1/2', 'tsp', 'salt', NULL, 8),
(71, 0.25, '1/4', 'tsp', 'black pepper', NULL, 9),
(71, 0.5, '1/2', 'tbsp', 'taco seasoning', NULL, 10),
(35, 3.0, NULL, 'clove', 'garlic', 'minced', 1),
(35, 1.0, NULL, 'tbsp', 'coriander', NULL, 2),
(35, 1.0, NULL, 'tbsp', 'cardamom', NULL, 3),
(35, 0.25, '1/4', 'tsp', 'cayenne pepper', NULL, 4),
(35, 1.0, NULL, 'tbsp', 'paprika', NULL, 5),
(35, 1.0, NULL, 'tsp', 'sumac', NULL, 6),
(35, 2.0, NULL, 'tsp', 'sea salt', NULL, 7),
(35, 2.0, NULL, 'tsp', 'sugar', NULL, 8),
(35, 1.0, NULL, NULL, 'whole lemon', 'juiced', 9),
(35, 0.3333, '1/3', 'cup', 'water', NULL, 10),
(35, 1.0, NULL, 'lb', 'boneless skinless chicken breast', NULL, 11),
(35, 2.0, NULL, 'lb', 'boneless skinless chicken thighs', NULL, 12),
(46, 2.0, NULL, 'lb', 'chicken breast', NULL, 1),
(46, 4.0, NULL, 'cup', 'chicken broth', NULL, 2),
(46, 16.0, NULL, 'oz', 'red enchilada sauce', NULL, 3),
(46, 28.0, NULL, 'oz', 'canned fire-roasted diced tomato', NULL, 4),
(46, 4.0, NULL, 'oz', 'canned fire-roasted green chiles', NULL, 5),
(46, 2.0, NULL, 'can', 'pinto beans', 'rinsed', 6),
(46, 1.0, NULL, NULL, 'white onion', 'chopped', 7),
(46, 2.0, NULL, 'clove', 'garlic', 'minced', 8),
(46, 1.0, NULL, NULL, 'jalapeno', 'chopped, de-seeded, deveined', 9),
(46, 8.0, NULL, NULL, 'corn tortillas', NULL, 10),
(46, NULL, NULL, NULL, 'cooking spray', NULL, 11),
(46, NULL, NULL, NULL, 'sea salt', NULL, 12),
(46, 2.0, NULL, NULL, 'avocados', 'optional topping; chopped', 13),
(46, 1.0, NULL, 'cup', 'cilantro', 'optional topping; chopped', 14),
(46, 1.0, NULL, 'cup', 'sour cream', 'optional topping, omit for dairy-free', 15),
(46, 1.0, NULL, 'cup', 'Mexican cheese', 'optional topping, omit for dairy-free', 16),
(46, 3.0, NULL, NULL, 'green onion', 'sliced for garnish', 17),
(43, 32.0, NULL, 'oz', 'frozen meatballs', 'precooked ONLY', 1),
(43, 1.0, NULL, NULL, 'yellow onion', 'chopped', 2),
(43, 3.0, NULL, 'clove', 'garlic', 'minced', 3),
(43, 2.0, NULL, 'can', 'canned diced tomatoes', NULL, 4),
(43, 4.0, NULL, 'cup', 'chicken or vegetable broth', NULL, 5),
(43, 4.0, NULL, 'cup', 'water', NULL, 6),
(43, 1.0, NULL, 'tbsp', 'italian seasonings', NULL, 7),
(43, 8.0, NULL, 'oz', 'chickpea pasta', NULL, 8),
(43, 3.0, NULL, 'cup', 'spinach', NULL, 9),
(43, 0.25, '1/4', 'cup', 'grated parmesan', 'optional garnish', 10),
(43, 0.25, '1/4', 'cup', 'fresh parsley and/or basil', 'optional garnish', 11),
(33, 1.75, '3/4', 'cup', 'unsalted chicken broth', NULL, 1),
(33, 1.0, NULL, 'cup', 'pesto sauce', 'divided', 2),
(33, 1.5, '1/2', 'lb', 'boneless skinless chicken thighs', NULL, 3),
(33, 1.5, '1/2', 'lb', 'boneless skinless chicken breast', NULL, 4),
(33, 8.0, NULL, 'oz', 'Brami high protein pasta', 'dry; see notes on pasta selection', 5),
(33, 3.0, NULL, 'cup', 'spinach', NULL, 6),
(33, 0.5, '1/2', 'cup', 'shredded mozzarella', NULL, 7),
(36, 16.0, NULL, 'oz', 'salsa verde', 'one 16 ounce jar', 1),
(36, 1.0, NULL, NULL, 'white onion', 'cut into strips', 2),
(36, 2.0, NULL, 'lb', 'chicken breast', 'defrosted', 3),
(34, 1.5, '1/2', 'lb', 'boneless', 'skinless chicken breast', 1),
(34, 1.5, '1/2', 'lb', 'boneless', 'skinless chicken thighs', 2),
(34, 3.0, NULL, 'clove', 'minced garlic', NULL, 3),
(34, 0.5, '1/2', 'cup', 'coconut aminos', NULL, 4),
(34, 0.3333, '1/3', 'cup', 'ketchup', NULL, 5),
(34, 0.25, '1/4', 'cup', 'honey', NULL, 6),
(34, 1.0, NULL, 'tbsp', 'rice vinegar', NULL, 7),
(34, 1.0, NULL, 'tbsp', 'cornstarch', NULL, 8),
(34, 1.0, NULL, 'tbsp', 'water', NULL, 9),
(34, NULL, NULL, NULL, 'sesame seeds', NULL, 10),
(34, NULL, NULL, NULL, 'green onion', NULL, 11),
(37, 3, NULL, 'lb', 'chicken wings', 'split, tips removed', 1),
(37, 1, NULL, 'cup', 'BBQ sauce', NULL, 2),
(37, 0.25, '1/4', 'cup', 'honey', NULL, 3),
(37, 2, NULL, 'tbsp', 'hot sauce', 'optional', 4),
(37, 1, NULL, 'tsp', 'garlic powder', NULL, 5),
(37, 1, NULL, 'tsp', 'smoked paprika', NULL, 6),
(37, NULL, NULL, NULL, 'salt and pepper', 'to taste', 7),
(38, 3, NULL, 'lb', 'pork shoulder', NULL, 1),
(38, 1, NULL, 'cup', 'BBQ sauce', NULL, 2),
(38, 0.5, '1/2', 'cup', 'chicken broth', NULL, 3),
(38, 1, NULL, 'tbsp', 'brown sugar', NULL, 4),
(38, 1, NULL, 'tsp', 'garlic powder', NULL, 5),
(38, 1, NULL, 'tsp', 'onion powder', NULL, 6),
(38, 1, NULL, 'tsp', 'smoked paprika', NULL, 7),
(38, NULL, NULL, NULL, 'salt and pepper', 'to taste', 8),
(38, NULL, NULL, NULL, 'butter lettuce leaves', 'for wrapping', 9),
(38, NULL, NULL, NULL, 'coleslaw mix', 'for topping', 10),
(45, 2, NULL, 'lb', 'boneless skinless chicken thighs', NULL, 1),
(45, 0.25, '1/4', 'cup', 'coconut aminos', NULL, 2),
(45, 2, NULL, 'tbsp', 'natural peanut butter', NULL, 3),
(45, 2, NULL, 'tbsp', 'lime juice', NULL, 4),
(45, 1, NULL, 'tbsp', 'honey', NULL, 5),
(45, 1, NULL, 'tbsp', 'rice vinegar', NULL, 6),
(45, 2, NULL, 'clove', 'garlic', 'minced', 7),
(45, 1, NULL, 'tsp', 'ginger', 'grated', 8),
(45, 1, NULL, 'tsp', 'sriracha', NULL, 9),
(45, NULL, NULL, NULL, 'butter lettuce leaves', NULL, 10),
(45, NULL, NULL, NULL, 'shredded carrots', 'topping', 11),
(45, NULL, NULL, NULL, 'cilantro', 'topping', 12),
(45, NULL, NULL, NULL, 'chopped peanuts', 'topping', 13),
(45, NULL, NULL, NULL, 'green onions', 'sliced, topping', 14),
(72, 2, NULL, NULL, 'eggs', 'large', 1),
(72, NULL, NULL, NULL, 'mushrooms', 'handful, sliced', 2),
(72, NULL, NULL, NULL, 'bell peppers', 'handful, sliced', 3),
(72, NULL, NULL, NULL, 'fresh spinach', 'handful', 4),
(72, 1, NULL, 'tsp', 'avocado oil', NULL, 5),
(72, NULL, NULL, NULL, 'salt and pepper', 'to taste', 6),
(73, 1, NULL, NULL, 'Awaken180 protein packet', 'vanilla or chocolate', 1),
(73, 3, NULL, 'tbsp', 'cold water', NULL, 2),
(73, NULL, NULL, NULL, 'cucumber or zucchini', 'finely diced', 3),
(73, NULL, NULL, NULL, 'cinnamon or nutmeg', 'to taste', 4),
(74, 2, NULL, NULL, 'eggs', 'or egg whites', 1),
(74, 1, NULL, 'cup', 'cauliflower rice', NULL, 2),
(74, NULL, NULL, NULL, 'spinach or cabbage', 'handful', 3),
(74, NULL, NULL, NULL, 'sea salt and pepper', 'to taste', 4),
(74, 1, NULL, 'tsp', 'avocado oil', NULL, 5),
(75, 1, NULL, 'cup', 'mixed diced vegetables', 'peppers, onion, zucchini, mushrooms', 1),
(75, 2, NULL, NULL, 'whole eggs', NULL, 2),
(75, 0.5, '1/2', 'cup', 'liquid egg whites', NULL, 3),
(75, NULL, NULL, NULL, 'sea salt', 'to taste', 4),
(75, NULL, NULL, NULL, 'black pepper', 'to taste', 5),
(75, NULL, NULL, NULL, 'garlic powder', 'to taste', 6),
(75, NULL, NULL, NULL, 'cooking spray', NULL, 7),
(1, 1, NULL, 'lb', 'ground turkey or beef', NULL, 1),
(1, 6, NULL, NULL, 'eggs', 'large', 2),
(1, 1, NULL, NULL, 'green bell pepper', 'diced', 3),
(1, 1, NULL, NULL, 'yellow onion', 'diced', 4),
(1, 1, NULL, 'cup', 'shredded cheddar cheese', NULL, 5),
(1, 8, NULL, NULL, 'flour tortillas', 'large, 10-inch', 6),
(1, 1, NULL, 'cup', 'frozen tater tots', 'baked', 7),
(1, NULL, NULL, NULL, 'salt and pepper', 'to taste', 8),
(1, NULL, NULL, NULL, 'cooking spray', NULL, 9);
-- touched
